In [ ]:
import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)
import matplotlib.pyplot as plt
from sklearn.neighbors import KNeighborsClassifier
from sklearn import preprocessing
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix


# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

In [ ]:
iris=pd.read_csv("/content/drive/MyDrive/Iris.csv",index_col=0)
iris.head()

SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
Id                                                                       
1             5.1           3.5            1.4           0.2  Iris-setosa
2             4.9           3.0            1.4           0.2  Iris-setosa
3             4.7           3.2            1.3           0.2  Iris-setosa
4             4.6           3.1            1.5           0.2  Iris-setosa
5             5.0           3.6            1.4           0.2  Iris-setosa

Data Visualiation and Analysis

In [ ]:
iris.shape

(150, 5)

In [ ]:
iris.drop('PetalLengthCm',axis=1,inplace=True)
df=iris.drop('PetalWidthCm',axis=1)

In [ ]:
df ['Species'].value_counts()

Iris-setosa        50
Iris-versicolor    50
Iris-virginica     50
Name: Species, dtype: int64

In [ ]:
df.columns

Index(['SepalLengthCm', 'SepalWidthCm', 'Species'], dtype='object')

In [ ]:
df.describe(include="all")

SepalLengthCm  SepalWidthCm      Species
count      150.000000    150.000000          150
unique            NaN           NaN            3
top               NaN           NaN  Iris-setosa
freq              NaN           NaN           50
mean         5.843333      3.054000          NaN
std          0.828066      0.433594          NaN
min          4.300000      2.000000          NaN
25%          5.100000      2.800000          NaN
50%          5.800000      3.000000          NaN
75%          6.400000      3.300000          NaN
max          7.900000      4.400000          NaN

In [ ]:
X=df.iloc[:,:2]
X.sample(4)

SepalLengthCm  SepalWidthCm
Id                              
69             6.2           2.2
105            6.5           3.0
147            6.3           2.5
96             5.7           3.0

In [ ]:
y=df['Species']
y.sample(3)

Id
72    Iris-versicolor
76    Iris-versicolor
23        Iris-setosa
Name: Species, dtype: object

In [ ]:
X

SepalLengthCm  SepalWidthCm
Id                              
1              5.1           3.5
2              4.9           3.0
3              4.7           3.2
4              4.6           3.1
5              5.0           3.6
..             ...           ...
146            6.7           3.0
147            6.3           2.5
148            6.5           3.0
149            6.2           3.4
150            5.9           3.0

[150 rows x 2 columns]

In [ ]:
model = KNeighborsClassifier(n_neighbors = 10, metric = 'minkowski', p = 2)
model.fit(X,y)

KNeighborsClassifier(n_neighbors=10)

In [ ]:
#Sample for Testing
sample = np.array([5.2,3.1])

In [ ]:
model.predict([sample])

/usr/local/lib/python3.10/dist-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but KNeighborsClassifier was fitted with feature names
  warnings.warn(


array(['Iris-setosa'], dtype=object)

Data Normaliation

In [ ]:
# print
X=preprocessing.StandardScaler().fit_transform(X)
X[:4]

array([[-0.90068117,  1.03205722],
       [-1.14301691, -0.1249576 ],
       [-1.38535265,  0.33784833],
       [-1.50652052,  0.10644536]])

Train Test split

In [ ]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=23)
y_test.shape

(30,)

In [ ]:
X_test

array([[ 1.2803405 ,  0.10644536],
       [ 1.64384411,  0.33784833],
       [-0.05250608, -0.8191665 ],
       [-1.50652052,  0.10644536],
       [-0.17367395, -1.28197243],
       [ 1.2803405 ,  0.10644536],
       [-0.17367395,  1.72626612],
       [ 0.67450115,  0.10644536],
       [-0.53717756,  0.80065426],
       [-0.29484182, -0.35636057],
       [ 0.31099753, -0.58776353],
       [-1.26418478,  0.10644536],
       [ 1.52267624, -0.1249576 ],
       [-0.90068117,  1.72626612],
       [-0.53717756,  1.49486315],
       [ 0.55333328, -0.58776353],
       [ 0.67450115,  0.33784833],
       [ 0.31099753, -0.35636057],
       [ 2.24968346, -0.1249576 ],
       [-0.7795133 ,  0.80065426],
       [ 0.67450115,  0.33784833],
       [-1.26418478, -0.1249576 ],
       [-0.90068117,  1.72626612],
       [-1.38535265,  0.33784833],
       [ 1.03800476,  0.10644536],
       [-0.90068117,  1.03205722],
       [-0.90068117,  1.72626612],
       [ 0.4321654 , -0.58776353],
       [ 0.91683689,

Training & Predicting

In [ ]:
knmodel=KNeighborsClassifier(n_neighbors=3)
knmodel.fit(X_train,y_train)
y_predict1=knmodel.predict(X_test)
X_test

array([[ 1.2803405 ,  0.10644536],
       [ 1.64384411,  0.33784833],
       [-0.05250608, -0.8191665 ],
       [-1.50652052,  0.10644536],
       [-0.17367395, -1.28197243],
       [ 1.2803405 ,  0.10644536],
       [-0.17367395,  1.72626612],
       [ 0.67450115,  0.10644536],
       [-0.53717756,  0.80065426],
       [-0.29484182, -0.35636057],
       [ 0.31099753, -0.58776353],
       [-1.26418478,  0.10644536],
       [ 1.52267624, -0.1249576 ],
       [-0.90068117,  1.72626612],
       [-0.53717756,  1.49486315],
       [ 0.55333328, -0.58776353],
       [ 0.67450115,  0.33784833],
       [ 0.31099753, -0.35636057],
       [ 2.24968346, -0.1249576 ],
       [-0.7795133 ,  0.80065426],
       [ 0.67450115,  0.33784833],
       [-1.26418478, -0.1249576 ],
       [-0.90068117,  1.72626612],
       [-1.38535265,  0.33784833],
       [ 1.03800476,  0.10644536],
       [-0.90068117,  1.03205722],
       [-0.90068117,  1.72626612],
       [ 0.4321654 , -0.58776353],
       [ 0.91683689,

In [ ]:
print(knmodel.predict([sample]))

['Iris-virginica']


Accuracy

In [ ]:
acc=accuracy_score(y_test,y_predict1)
acc

0.7666666666666667

Confusion matrix


In [ ]:
cm=confusion_matrix(y_test.values,y_predict1)
cm

array([[12,  0,  0],
       [ 0,  4,  4],
       [ 0,  3,  7]])